version: "3.8"

services:
  # Сервіс для застосунку
  app:
    build: .
    container_name: python_web_hw_2_app_container
    ports:
      - "8081:8000" # Проксіювання порту 8081 на хості до порту 8000 в контейнері
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
    depends_on:
      - db # Залежність від сервісу бази даних

  # Сервіс для PostgreSQL
  db:
    image: postgres:13
    container_name: db_python_web_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5433:5432"
